name: Build NetSecureBotChat

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build Solution
        run: dotnet build "Net Bot App.sln" --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish "Net Bot App/Net Bot App.csproj" -c Release -o publish

      - name: Upload Published Files
        uses: actions/upload-artifact@v4
        with:
          name: NetSecureBotChat
          path: publish
